# Generated by Django 3.0.6 on 2020-08-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0003_auto_20200813_2239'),
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='faved_books',
            field=models.ManyToManyField(related_name='favorited_books', to='log_reg_app.User'),
        ),
    ]
