# Generated by Django 3.0.6 on 2020-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
