# Generated by Django 3.0.6 on 2020-08-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_comment',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_message', to='wallapp.Wall_Message'),
        ),
    ]
