# Generated by Django 3.0.6 on 2020-08-21 22:31

from django.db import migrations, models
import fileapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=fileapp.models.upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
